// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCsXJBpUigAHJFjxtm2lN2Tna_-0KAFTM',
    appId: '1:919843880991:web:d34dd39343d73d00bcd52a',
    messagingSenderId: '919843880991',
    projectId: 'classactivity14-c28ab',
    authDomain: 'classactivity14-c28ab.firebaseapp.com',
    storageBucket: 'classactivity14-c28ab.firebasestorage.app',
    measurementId: 'G-8KCHECWFLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUlzNAWogPIW5l8oDCsGsFTPwpGPG39uQ',
    appId: '1:919843880991:android:1a470f741d2e2fc3bcd52a',
    messagingSenderId: '919843880991',
    projectId: 'classactivity14-c28ab',
    storageBucket: 'classactivity14-c28ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC51QILkeQUI_RILoX4flJr6-whfjPVjic',
    appId: '1:919843880991:ios:f2fc1bf976b1fb7dbcd52a',
    messagingSenderId: '919843880991',
    projectId: 'classactivity14-c28ab',
    storageBucket: 'classactivity14-c28ab.firebasestorage.app',
    iosBundleId: 'com.example.classactivity14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC51QILkeQUI_RILoX4flJr6-whfjPVjic',
    appId: '1:919843880991:ios:f2fc1bf976b1fb7dbcd52a',
    messagingSenderId: '919843880991',
    projectId: 'classactivity14-c28ab',
    storageBucket: 'classactivity14-c28ab.firebasestorage.app',
    iosBundleId: 'com.example.classactivity14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCsXJBpUigAHJFjxtm2lN2Tna_-0KAFTM',
    appId: '1:919843880991:web:2cc9459fb7f0815dbcd52a',
    messagingSenderId: '919843880991',
    projectId: 'classactivity14-c28ab',
    authDomain: 'classactivity14-c28ab.firebaseapp.com',
    storageBucket: 'classactivity14-c28ab.firebasestorage.app',
    measurementId: 'G-H3BFMHBCFS',
  );
}
